### ISSUE TITLE
socket_handler

### ISSUE THREAD

**Issue by ncfex** [aitsis/ait-ui#44]
# GLOBAL PROPERTIES -------------------------------------------------------------------------------
    @property
    def webserver(self):
        return socket_handler.web_server

    @property
    def web_request(self):
        return socket_handler.web_request
        
Element class ı içerisindeki socket_handler ın artık kullanılmadığı için düzenlenmesi gerekiyor.

orn:
#elements/file.py
self.webserver.add_url_rule('/file-upload', 'upload', self.upload, methods=['POST'])

Bu kısım hata veriyor.

socket_handler düzenlenecek.

**Comment by hozgur** [comment]
Evet ben kaldıracaktım unutmuşum

**Comment by hozgur** [comment]
kaldirdim.
